### ISSUE TITLE
icd codes not found

### ISSUE THREAD

**Issue by OpenCodeJourney** [lhncbc/clin-table-search#1]
Hi,
I have tried to search some clinical terms like "lung cancer" but auto complete search is not giving any result. 

Thanks,
Harry

**Comment by plynchnlm** [comment]
That indicates there are no ICD codes that contain both the words "lung" and "cancer".  Which API were you using?  ICD-10-CM?

**Comment by plynchnlm** [comment]
If you try our "conditions" API, that one does have "lung cancer" as an entry, and also has the relevant ICD-10-CM code.  (See https://clinicaltables.nlm.nih.gov/demo.html?db=conditions, and check both "consumer name" and icd10cm in the "display" field list).  However, note that the "conditions" API is meant to be a list of commonly occurring medical conditions, and not a complete source of ICD-10-CM codes.

**Comment by plynchnlm** [comment]
Closing due to lack of response.
