### ISSUE TITLE
More than 500 search results

### ISSUE THREAD

**Issue by gaboc623** [lhncbc/clin-table-search#10]
Would it be possible to get more than 500 results when using the API, there seem to be search terms that have more than the 500 result limit but I cannot retrieve all of the results.

**Comment by plynchnlm** [comment]
What is the case when 500 results from a search would not be enough?  If you are trying to download the dataset, it is better to get if from the source, for which there are links in the Details column at https://clinicaltables.nlm.nih.gov/.

**Comment by gaboc623** [comment]
Thank you for pointing in me in the direction of that data!

**Comment by plynchnlm** [comment]
FYI, we do now provide an offset parameter, though the total of count+offset is limited to 7500.
