### ISSUE TITLE
incorrect address formatting

### ISSUE THREAD

**Issue by compwron** [lhncbc/clin-table-search#11]
We call `https://clinicaltables.nlm.nih.gov/api/npi_idv/v3/search?terms=` many times a day and every so often (once a week or so) we get back a result which is formatted wrongly in that instead of retuning stringified json in the address field, it returns a plan address not stored as json- i.e. a plain `2010 OPPORTUNITY LANE, GLIDE, OR 97443` instead of `"{\"line1\":\"123 PARK AVE\",\"line2\":\"APT 7\",\"city\":\"NEW YORK\",\"state\":\"NY\",\"zip\":\"10010\",\"country\":\"US\",\"phone\":\"(555) 555-5555\"}"],`

<img width="261" alt="Screen Shot 2022-11-03 at 4 51 25 PM" src="https://user-images.githubusercontent.com/578159/199856293-bf5ee0e0-2278-4fd4-adf7-92d1017af58f.png">
<img width="883" alt="Screen Shot 2022-11-03 at 4 58 57 PM" src="https://user-images.githubusercontent.com/578159/199857046-17b327e4-443e-4cd8-bd42-a36f1ca18efc.png">

**Comment by plynchnlm** [comment]
Offhand I can't think why that would be happening.  Can you share a specific example of a clinicaltables query that returns data that causes that problem?

**Comment by plynchnlm** [comment]
Closing due to lack of response.
