### ISSUE TITLE
NASH Nonalcoholic steatohepatitis not showing 

### ISSUE THREAD

**Issue by scdev01** [lhncbc/clin-table-search#12]
Hi, it appears the dataset for (API for Medical Conditions) is missing the following medical condition NASH Nonalcoholic steatohepatitis. For reference this is the API Base URL: API Base URL: https://clinicaltables.nlm.nih.gov/api/conditions/v3/search (+ [query string parameters](https://clinicaltables.nlm.nih.gov/apidoc/conditions/v3/doc.html#params))

When I try to look up Fatty liver or NASH nothing comes up.

**Comment by plynchnlm** [comment]
Thanks for reporting that.  We'll add it.

**Comment by plynchnlm** [comment]
NASH has been added.  Thanks again for pointing it out.
