### ISSUE TITLE
Individual NPI API returns malformed taxonomy JSON string

### ISSUE THREAD

**Issue by kevinfguo** [lhncbc/clin-table-search#14]
## Issue Summary
When using the [NPI Records - Individuals](https://clinicaltables.nlm.nih.gov/apidoc/npi_idv/v3/doc.html) API, I noticed that including `df=licenses` returns malformed JSON for providers with multiple licenses. 

For example, [this search](https://clinicaltables.nlm.nih.gov/api/npi_idv/v3/search?df=NPI,licenses&sf=NPI,name.full&terms=john+marasigan) returns:
```
"{\"taxonomy\":{\"code\":\"225100000X\",\"grouping\":\"Respiratory, Developmental, Rehabilitative and Restorative Service Providers\",\"classification\":\"Physical Therapist\",\"path\":\"Respiratory, Developmental, Rehabilitative and Restorative Service Providers\\\\Physical Therapist\"},\"lic_number\":\"070.018396\",\"lic_state\":\"IL\",\"is_primary_taxonomy\":\"Y\",\"medicare\":[{\"spc_code\":\"65\",\"type\":\"Physical Therapist in Private Practice\"}]},{\"taxonomy\":{\"code\":\"225100000X\",\"grouping\":\"Respiratory, Developmental, Rehabilitative and Restorative Service Providers\",\"classification\":\"Physical Therapist\",\"path\":\"Respiratory, Developmental, Rehabilitative and Restorative Service Providers\\\\Physical Therapist\"},\"lic_number\":\"029892-1\",\"lic_state\":\"NY\",\"is_primary_taxonomy\":\"N\",\"medicare\":[{\"spc_code\":\"65\",\"type\":\"Physical Therapist in Private Practice\"}]}"
```
Which cannot be parsed, unless the string is wrapped with a `[` and `]` after/before the start/end quotes, respectively.

## Proposal
Outside of just returning a parseable JSON string, I'd suggest this tuple value was directly returned as a list of `taxonomy` objects.

### Other
I'd like to thank the builders and maintainers of this Clinical Table Search Service. This is a great and refreshing service being provided to the public. I cannot imagine how many different groups out there have had to roll their own service wrappers around these data sets; having the NIH/NLM provide this goes a long way to helping access, availability, and innovation in the clinical and medical space.

**Comment by xluanlhc** [comment]
Hi Kevin,

Thank you very much for the feedback, we are glad to hear that you like the service!
For the specific issue, a workaround is to use the "ef" (extra fields) parameter, e.g., "&ef=licenses" to retrieve the licenses json object. 

The "df" is intended to return a "flat" list of string-valued fields for use in autocomplete and other simple use cases. Hope that helps, please don't hesitate to contact us if you have any questions, suggestions, or concerns.

Thanks!
Xiaocheng Luan

**Comment by kevinfguo** [comment]
Hi Xiaocheng,

Got it, that's helpful. The "flat" intent was not obvious from the docs, so didn't read about `ef` carefully. I also see now in the docs that
>...fields (or their requested aliases) named in the "ef" parameter, and the value for a field is an array of that field's values in the same order as the returned codes.

So this seems workable. 

I think having the requested `ef` properties all in a list of objects with all those `ef` properties would be more intuitive (aka grouped by distinct result):
```
[
  {
    "name": {...}, // e.g. Jane Doe
    "licenses": [...]
  },
  {
    "name": {...}, // e.g. John Smith
    "licenses": [...]
  }
]
```

rather than objects with the `ef` properties as keys with list values (aka grouped by property, currently). But nothing a little post-processing can't fix on my end.

Thanks!
Kevin

**Comment by xluanlhc** [comment]
Hi Kevin,

Yes, I agree - thanks for the feedback and great thoughts. We have a ticket opened to update the documentation on df & ef.

Regarding the organization of the ef values, there are discussions on a new API response format where the data elements of a result item are organized as one object, which would be in line with what you are suggesting. But due to limited resources and other priorities, we can not promise when or whether such a new feature will be implemented. 

Again, we greatly appreciate your feedback.

Thanks,
Xiaocheng
