### ISSUE TITLE
ICD10 for Covid not updatd. 

### ISSUE THREAD

**Issue by rmclellanduhin** [lhncbc/clin-table-search#2]

**Comment by rmclellanduhin** [comment]
The CDC added a new code for Covid, but its not pulling up U07.1

**Comment by plynchnlm** [comment]
Thanks for pointing that out.  The CDC has not released new data files that include this new code, but we will try to add it manually.

**Comment by rmclellanduhin** [comment]
Thank you. Any idea on a timeline for it to be added manually?

**Comment by plynchnlm** [comment]
Hopefully this afternoon.

**Comment by plynchnlm** [comment]
It is up now.
