### ISSUE TITLE
API doesn't give medication strength for some medicine

### ISSUE THREAD

**Issue by hariveluwbc** [lhncbc/clin-table-search#3]
Hi ,
https://clin-table-search.lhc.nlm.nih.gov/api/rxterms/v3/search?ef=STRENGTHS_AND_FORMS,RXCUIS&maxList=&terms=Hyoscyamine/Methenamine/Methylene blue/Phenyl salicylate/Sodium Phosphate, Monobasic (Oral Pill)

I faced strange issue when calling API . I didn't get any data by using above url.
When we remove the last character from above url,it works fine .
for example,
https://clin-table-search.lhc.nlm.nih.gov/api/rxterms/v3/search?ef=STRENGTHS_AND_FORMS,RXCUIS&maxList=&terms=Hyoscyamine/Methenamine/Methylene blue/Phenyl salicylate/Sodium Phosphate, Monobasic (Oral Pill

Actually i need medication strength for medicine "Hyoscyamine/Methenamine/Methylene blue/Phenyl salicylate/Sodium Phosphate, Monobasic (Oral Pill)"

[](url)

**Comment by hariveluwbc** [comment]
Hi,
I found fix, now used double quotes in terms to resolve this
Example:
https://clin-table-search.lhc.nlm.nih.gov/api/rxterms/v3/search?ef=STRENGTHS_AND_FORMS,RXCUIS&maxList=&terms="Hyoscyamine/Methenamine/Methylene blue/Phenyl salicylate/Sodium Phosphate, Monobasic (Oral Pill)"

**Comment by plynchnlm** [comment]
This was fixed.  I'm sorry for not updating the issue sooner.
