### ISSUE TITLE
Unable to filter data from FHIR URL

### ISSUE THREAD

**Issue by santoshjami** [lhncbc/clin-table-search#4]
This below FHIR API is returning 0 results.
https://clinicaltables.nlm.nih.gov/fhir/STU3/ValueSet/icd10cm/$expand?filter=cholera&_format=json&count=5

If I removed the "filter" param, it looks alright again:
https://clinicaltables.nlm.nih.gov/fhir/STU3/ValueSet/icd10cm/$expand?_format=json&count=5

Also, Is there a way to download the capability statement of the above published FHIR terminology service?

**Comment by plynchnlm** [comment]
Sorry for the very delayed reply.  I missed the alert for this issue and am just now seeing it.  I agree that should match.  The reason it does not is that that API by default only matches on the "code" field, and not the "name" field (which are documented at https://clinicaltables.nlm.nih.gov/apidoc/icd10cm/v3/doc.html).

To make it match on either, you can use:  https://clinicaltables.nlm.nih.gov/fhir/R4/ValueSet/$expand?url=http://clinicaltables.nlm.nih.gov/fhir/R4/ValueSet/icd10cm%3Fsf%3Dcode,name

I think we should make this the default behavior for the $expand operation.

**Comment by xluanlhc** [comment]
> This below FHIR API is returning 0 results.
> https://clinicaltables.nlm.nih.gov/fhir/STU3/ValueSet/icd10cm/$expand?filter=cholera&_format=json&count=5
> 
> If I removed the "filter" param, it looks alright again:
> https://clinicaltables.nlm.nih.gov/fhir/STU3/ValueSet/icd10cm/$expand?_format=json&count=5

This filter issue has been fixed. Thanks for the feedback and sorry for the delayed response.

> Also, Is there a way to download the capability statement of the above published FHIR terminology service?

Not at this point, we'll put it on our backlog but there is no plan to address the issue in the near term. Please let us know if this is a significant issue in your use cases and we may reassess.
