### ISSUE TITLE
New ICD10 for Covid not in database

### ISSUE THREAD

**Issue by chris-livecare** [lhncbc/clin-table-search#7]
https://www.cdc.gov/nchs/data/icd/Announcement-New-ICD-code-for-coronavirus-19-508.pdf

• Encounter for screening for COVID-19 (Z11.52)
• Contact with and (suspected) exposure to COVID-19 (Z20.822)
• Personal history of COVID-19 (Z86.16)
• Multisystem inflammatory syndrome (MIS) (M35.81)
• Other specified systemic involvement of connective tissue (M35.89)
• Pneumonia due to coronavirus disease 2019 (J12.82)

**Comment by xluanlhc** [comment]
Thanks for reporting the issue. We'll look into it and update to include the latest data release.
Xiaocheng

**Comment by xluanlhc** [comment]
Thanks again for reporting the issue, it has been fixed and the fix is live. Please feel free to contact us if you see further issues.
